workflows:
  android-build:
    name: Fix Build APK
    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - name: Setup
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Install Gradle
        script: |
          sdk install gradle

      - name: Build APK
        script: |
          gradle build
          gradle assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk
